### ISSUE TITLE
destroying airbase crashes the game

### ISSUE THREAD

**Issue by falconner** [munawarb/Three-D-Velocity#93] opened 2019-08-11 15:22 UTC
When playing in the mission mode, in the latest version, as soon as the airbase is destroyed, the game closes after the cutseen.
 Suspect its not able to create fighters for whatever reason.
log is here.

> 
[errorAug-4-2019 8-51-3 PM-0.log](https://github.com/munawarb/Three-D-Velocity/files/3490137/errorAug-4-2019.8-51-3.PM-0.log)

**Comment by Addolis** [comment] 2019-08-25 21:01
Sorry for the duplicate.
Is there any fix for this, or is it just broken for now? When I try and update the game, I get an error as well..

**Comment by munawarb** [comment] 2019-08-25 21:31
Hi @Addolis,
No worries. There's no fix for it yet that I've committed. I'll work on it once I'm done upgrading TDV to XAudio2.

**Comment by nickgaw** [comment] 2019-08-30 18:59
I was in the very last fight of the game after the audio file plays and the game crashed with this error.
Error log, created with build version 2.31.0.0: 
Error base exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TDV.Mission.createNewFighter(Int32 type, Int32 radius) in C:\Users\munawar\projects\Three-D-Velocity\TDV\Mission.cs:line 495
   at TDV.JuliusAircraft.move() in C:\Users\munawar\projects\Three-D-Velocity\TDV\JuliusAircraft.cs:line 113
   at TDV.Holder.activate() in C:\Users\munawar\projects\Three-D-Velocity\TDV\Holder.cs:line 106
Error Description: Object reference not set to an instance of an object.
Stack trace:    at TDV.Mission.createNewFighter(Int32 type, Int32 radius) in C:\Users\munawar\projects\Three-D-Velocity\TDV\Mission.cs:line 495
   at TDV.JuliusAircraft.move() in C:\Users\munawar\projects\Three-D-Velocity\TDV\JuliusAircraft.cs:line 113
   at TDV.Holder.activate() in C:\Users\munawar\projects\Three-D-Velocity\TDV\Holder.cs:line 106

**Comment by munawarb** [comment] 2019-08-30 22:37
This problem is caused by the same issue that @falconner pointed out, so closing the issue will fix the end of game crash as well.

**Closed** 2019-08-31 22:05 UTC
Labels: bug
