### ISSUE TITLE
Problem with bots in multiplayer

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#37] opened 2018-05-06 12:04 UTC
When a bot kills you then you join back in free for all, the bot gets stuck in the ground and does nothing. You have to kick it.

**Comment by munawarb** [comment] 2018-05-07 01:06
Hi @burakyuksek, I'm not able to reproduce this and I tried multiple times. Are you running the latest version of the game?

I spun up a local server and added several bots. I waited for them to kill each other off and when a few were remaining I exited and rejoined. It worked fine.

**Comment by munawarb** [comment] 2018-06-26 15:58
Closing because I can't reproduce this one and there was no follow-up for some time.

**Closed by munawarb** 2018-06-26 15:58 UTC
Labels: Can't Reproduce
