### ISSUE TITLE
Can't get by the airbase

### ISSUE THREAD

**Issue by Addolis** [munawarb/Three-D-Velocity#96] opened 2019-08-25 20:44 UTC
Hello,
I have downloaded the latest version of the TDV zip file, and extracted it.
However, when I get past the airbase, right after the cut sceen, the game crashes, and I'm stuck.
I was one of the one's who paid for an origional TDV 2 lisence, before it became open source.
What steps do I need to take to resolve the issue?
Thanks,
Darrell

**Comment by munawarb** [comment] 2019-08-25 20:46
This is a duplicate of #93 .

**Closed** 2019-08-31 22:05 UTC
Labels: duplicate
