### ISSUE TITLE
Music Raises to Full Upon Window Regaining Focus

### ISSUE THREAD

**Issue by ironcross32** [munawarb/Three-D-Velocity#81] opened 2019-03-19 04:19 UTC
Music volume should persist across game window losing and regaining focus, such as in ALT tabbing away from the window and back in; currently, the music usually returns to full volume.

**Comment by munawarb** [comment] 2019-07-28 18:29
I'm not able to reproduce this, but I do see a case where the music could go higher than the set level because it's not normalized. Your use of the word "usually" is noted. This leads me to believe that it's only happening sometimes. hopefully it's fixed now.

**Closed** 2019-07-28 18:32 UTC
Labels: bug
