### ISSUE TITLE
Game receives input even when it's window is not active

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#72] opened 2018-11-22 17:06 UTC
Hello,
Try the following:
1. Connect to a lobby of a multiplayer game
2. Alt+tab away
3. Press w
The game asks who we want to send a pm to.

**Comment by munawarb** [comment] 2018-12-04 20:47
Hi @burakyuksek , I'm not able to reproduce this. The keyboard by design is no longer polled once TDV loses focus, so I'm not sure how this happened in your case. TDV only reading keys when it's in the foreground is controlled by `DirectInput`.

Does this happen consistently?

**Comment by burakyuksek** [comment] 2018-12-07 19:47
Hello,
Yes this is consistent. This mostly seems to happen in the hangar menu. I am using the latest version.

**Comment by munawarb** [comment] 2018-12-07 21:08
It seems like it was fixed in dbf5a64. I can't reproduce it here using the new `BPCSharedComponent.dll`.

**Closed by munawarb** 2018-12-07 21:08 UTC
