### ISSUE TITLE
the game crashes when i destro the air base.

### ISSUE THREAD

**Issue by vlad-a-c** [munawarb/Three-D-Velocity#98] opened 2019-09-01 02:35 UTC
when i destroy the air base, it plays the cut scene in mission mode when it asks me to go to ze19 and then it generates an error. here it is.
[errorSep-1-2019 5-29-49 AM-0.log](https://github.com/munawarb/Three-D-Velocity/files/3563047/errorSep-1-2019.5-29-49.AM-0.log)

**Comment by munawarb** [comment] 2019-09-01 11:30
Duplicate of #93 . This issue is already resolved and the fix will be available in the next binary release.

**Closed by munawarb** 2019-09-01 11:30 UTC
Labels: duplicate

**Comment by vlad-a-c** [comment] 2019-09-01 12:08
oh sorry. i didn't see it. but there's another problem. i've rebuilt the thing from the actual sourcecode but now i die way too easy.

**Comment by munawarb** [comment] 2019-09-01 13:53
Hi @vlad-a-c,
Ok. Try compiling with the latest master branch or get the binaries. It should be working fine now. I made some last-minute pushes recently.

**Comment by vlad-a-c** [comment] 2019-09-01 14:08
like i said, the damage is way bigger than it was before. i'm daying after the first rocket hit. i don't know who played with it or what happened exactly but the thing is kind of unplayable. also, when the after burners are on the pitch doesn't increase anymore.

**Comment by munawarb** [comment] 2019-09-01 16:25
Hi,
I don't recall playing with damage points at all. So not sure what you're seeing there. Sorry I can't be of more assistance on this issue.
