### ISSUE TITLE
Still can not get TDV.EXE to work.

### ISSUE THREAD

**Issue by blindpilot** [munawarb/Three-D-Velocity#9] opened 2017-02-03 20:59 UTC
> Hello to you Munawar. 
I have down loaded the following compressed folder. 
Three-D-Velocity-1.0.zip
Now there are two exe files in this compressed folder. 
They are as follows: 
tdv.exe with a long string of numbers and letters after it. 
Then if I down arrow twice I see a second exe file which is as follows: 
tdv.pdb
Now, I think I'm seeing why I can not launch the tdv.exe file like I'm suppose to be able to. 
It is looking like I'm having a smart screen interfearing with the launching of the tdv.exe file. 
How can I fix this issue so that I may be able to launce and or install TDV? 
Many Thanks. 
Ron Kolesar.

**Comment by munawarb** [comment] 2017-02-04 16:50
Duplicate of #8.

**Closed by munawarb** 2017-02-04 16:50 UTC
Labels: duplicate
